# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brainless Developer
author: Fausto NA
author_link: https://github.com/brainlessdeveloper
author_description: >
  I am a web developer based in Berlin.
  At the moment I am working for store2be, a booking platform for promotion and retail locations.
  We work with React, Ruby on Rails and sometimes Rust. Also, I love everything
  about web development even if it's design-oriented so expect all sorts of topics.
email: fausto.nunez@outlook.com
description: >
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://brainlessdeveloper.com" # the base hostname & protocol for your site

# Picturefill
# A responsive image polyfill: http://scottjehl.github.io/picturefill/
picturefill: false

# Typography
# To use, publish a kit and enter the ID here. If you do not wish to use Typekit,
# leave this ID blank
typekit_kit_id:

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
  style: :compressed
