# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fausto's personal website
author: Fausto Núñez Alberro
author_link: https://github.com/fnune
author_description: >
  I am a web developer based in Berlin.
  At the moment I am working for store2be, a booking platform for promotion and retail locations.
  We work with React, Ruby on Rails and sometimes Rust. Also, I love everything
  about web development even if it's design-oriented so expect all sorts of topics.
email: fausto.nunez@outlook.com
description: >
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fnune.com" # the base hostname & protocol for your site

# Build settings
plugins: [jekyll-sitemap]
markdown: kramdown
permalink: pretty

# Sass
sass:
  style: :compressed

# Sitemap
sitemap:
  filename: "/sitemap.xml"
  exclude:
      - "/atom.xml"
      - "/feed.xml"
      - "/feed/index.xml"
      - "/css/screen.scss"
  include_posts:
      - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"
